language: generic

sudo: required

services:
  - docker

before_install:
  - docker info
  - docker build -t android-21 android-21/

script:
  - docker run -it --rm --privileged --volume=$(pwd)/android-21:/opt/workspace --entrypoint /opt/workspace/version-check.sh android-21
