dist: xenial

language: generic

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
# EMULATOR_API_LEVEL=14 x86 is not published. 
  - EMULATOR_API_LEVEL=15 EMULATOR_ARCH=x86
  - EMULATOR_API_LEVEL=16 EMULATOR_ARCH=x86
  - EMULATOR_API_LEVEL=17 EMULATOR_ARCH=x86
  - EMULATOR_API_LEVEL=18 EMULATOR_ARCH=x86
  - EMULATOR_API_LEVEL=19 EMULATOR_ARCH=x86
# EMULATOR_API_LEVEL=20 is not published at all.
  - EMULATOR_API_LEVEL=21 EMULATOR_ARCH=x86_64
  - EMULATOR_API_LEVEL=22 EMULATOR_ARCH=x86_64
  - EMULATOR_API_LEVEL=23 EMULATOR_ARCH=x86_64
  - EMULATOR_API_LEVEL=24 EMULATOR_ARCH=x86_64
  - EMULATOR_API_LEVEL=25 EMULATOR_ARCH=x86_64
  - EMULATOR_API_LEVEL=26 EMULATOR_ARCH=x86_64   
  - EMULATOR_API_LEVEL=27 EMULATOR_ARCH=x86   
  - EMULATOR_API_LEVEL=28 EMULATOR_ARCH=x86_64

before_install:
  - docker info

script:
  - docker build --build-arg EMULATOR_API_LEVEL --build-arg EMULATOR_ARCH -t android-emulator-$EMULATOR_API_LEVEL android-emulator/
  - docker run -it --rm --env EMULATOR_API_LEVEL --volume=$(pwd)/android-emulator:/opt/workspace --entrypoint /opt/workspace/start-emulator.sh android-emulator-$EMULATOR_API_LEVEL
