language: generic

sudo: required

services:
  - docker

env:
  - EMULATOR_SDK_VERSION=21
  - EMULATOR_SDK_VERSION=22
  - EMULATOR_SDK_VERSION=23
  - EMULATOR_SDK_VERSION=24
  - EMULATOR_SDK_VERSION=25
  - EMULATOR_SDK_VERSION=26    
  - EMULATOR_SDK_VERSION=27    
  - EMULATOR_SDK_VERSION=28

before_install:
  - docker build --build-arg EMULATOR_SDK_VERSION -t android-emulator-$EMULATOR_SDK_VERSION android-emulator/

script:
  - docker run -it --rm --env EMULATOR_SDK_VERSION --volume=$(pwd)/android-emulator:/opt/workspace --entrypoint /opt/workspace/start-emulator.sh android-emulator-$EMULATOR_SDK_VERSION
