language: generic

sudo: required

services:
  - docker

before_install:
- docker build -t android-25 android-25/

script:
- docker run -it --rm --volume=$(pwd)/android-25:/opt/workspace --entrypoint /opt/workspace/version-check.sh android-25