# https://docs.travis-ci.com/user/languages/minimal-and-generic/
language: minimal

services:
  - docker

env:
# EMULATOR_API_LEVEL=14 x86 is not published. 
  - EMULATOR_API_LEVEL=15 EMULATOR_VARIANT=google_apis EMULATOR_ARCH=x86
  - EMULATOR_API_LEVEL=16 EMULATOR_VARIANT=google_apis EMULATOR_ARCH=x86
  - EMULATOR_API_LEVEL=17 EMULATOR_VARIANT=google_apis EMULATOR_ARCH=x86
  - EMULATOR_API_LEVEL=18 EMULATOR_VARIANT=google_apis EMULATOR_ARCH=x86
  - EMULATOR_API_LEVEL=19 EMULATOR_VARIANT=google_apis EMULATOR_ARCH=x86
# EMULATOR_API_LEVEL=20 is not published at all.
  - EMULATOR_API_LEVEL=21 EMULATOR_VARIANT=google_apis EMULATOR_ARCH=x86_64
  - EMULATOR_API_LEVEL=22 EMULATOR_VARIANT=google_apis EMULATOR_ARCH=x86_64
  - EMULATOR_API_LEVEL=23 EMULATOR_VARIANT=google_apis EMULATOR_ARCH=x86_64
  - EMULATOR_API_LEVEL=24 EMULATOR_VARIANT=google_apis EMULATOR_ARCH=x86_64
  - EMULATOR_API_LEVEL=25 EMULATOR_VARIANT=google_apis EMULATOR_ARCH=armeabi-v7a
  - EMULATOR_API_LEVEL=25 EMULATOR_VARIANT=google_apis EMULATOR_ARCH=x86_64
  - EMULATOR_API_LEVEL=26 EMULATOR_VARIANT=google_apis EMULATOR_ARCH=x86_64
  - EMULATOR_API_LEVEL=27 EMULATOR_VARIANT=google_apis EMULATOR_ARCH=x86
  - EMULATOR_API_LEVEL=28 EMULATOR_VARIANT=google_apis EMULATOR_ARCH=x86_64

before_install:
  - docker info

script:
  - docker build --build-arg EMULATOR_API_LEVEL --build-arg EMULATOR_VARIANT --build-arg EMULATOR_ARCH -t android-emulator-$EMULATOR_API_LEVEL android-emulator/
  - docker run -it --rm --env EMULATOR_API_LEVEL --volume=$(pwd)/android-emulator:/opt/workspace --entrypoint /opt/workspace/start-emulator.sh android-emulator-$EMULATOR_API_LEVEL
