language: generic

sudo: required

services:
  - docker

before_install:
  - docker info
  - docker build -t android-27 android-27/

script:
  - docker run -it --rm --volume=$(pwd)/android-27:/opt/workspace --entrypoint /opt/workspace/version-check.sh android-27
